### PR TITLE
CBTL/SubmitBasketIncreaseTimeOut

### PR DESCRIPTION
**Pull request by abdul-rehman**
@misterwell 

- [CBTLIO-3562: Increase time out for submit order calls depending on POS worst case scenario](https://hathway.atlassian.net/browse/CBTLIO-3562)

### CODE REVIEW

**Comment by abdul-rehman** [comment]
As per @misterwell  directions to not update the existing functions. Purpose was to minimize the regression risk.

**Comment by awall1** [comment]
@abdul-rehman agreed but having an optional parameter means that it accounts for the cases that already existed that don't include the parameter. 
@misterwell do you have an opinion on this?

**Comment by misterwell** [comment]
My ask is that we make this change by overloading existing functions so that no code needs to change in existing applications (but then they don't necessarily get the benefit of timeout customization). 

The thing that I don't like about this PR as it stands is that it copies business logic rather than overloaded functions using the other functions. i.e. `submitSyncRequest` should have one core `submitSyncFunction` with all parameters included in the definition, and then overloaded functions (variants that are missing params or have optional params) should call that core function rather than re-implement the logic in each specific function.

**Comment by awall1** [comment]
#22 opened instead. I'm closing

**Comment by abdul-rehman** [comment]
Ohh sorry @misterwell  i miss understood that one.

**Pull request closed without merging**
